#!/usr/bin/env bash

set -euo pipefail

DEPLOYMENT_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
readonly DEPLOYMENT_ROOT
readonly VERSIONS_FILE="${DEPLOYMENT_ROOT}/VERSIONS.lock"

die() {
    printf 'error: %s\n' "$*" >&2
    exit 1
}

info() {
    printf '==> %s\n' "$*"
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

require_positive_integer() {
    local name="$1"
    local value="$2"
    [[ "${value}" =~ ^[0-9]+$ ]] || die "${name} must be numeric"
    ((value > 0)) || die "${name} must be greater than zero"
}

load_versions() {
    [[ -f "${VERSIONS_FILE}" ]] || die "missing ${VERSIONS_FILE}"
    # This file is tracked in the repository and contains assignments only.
    # shellcheck disable=SC1090
    source "${VERSIONS_FILE}"

    : "${NETWORK_ID:?NETWORK_ID must be locked}"
    : "${ECASH_NODE_CHAIN:?ECASH_NODE_CHAIN must be locked}"
    : "${ECASH_NETWORK_MAGIC:?ECASH_NETWORK_MAGIC must be locked}"
    : "${ECASH_PUBLIC_PEERS:?ECASH_PUBLIC_PEERS must be locked}"
    : "${ECASH_NODE_P2P_PORT:?ECASH_NODE_P2P_PORT must be locked}"
    : "${ECASH_NODE_RPC_PORT:?ECASH_NODE_RPC_PORT must be locked}"
    : "${ECASH_NODE_ZMQ_PORT:?ECASH_NODE_ZMQ_PORT must be locked}"
    : "${ECASH_NODE_EXPECTED_VERSION:?ECASH_NODE_EXPECTED_VERSION must be locked}"
    : "${ECASH_TIP_HEIGHT_URL:?ECASH_TIP_HEIGHT_URL must be locked}"
    : "${ECASH_EXPECTED_DATA_BYTES:?ECASH_EXPECTED_DATA_BYTES must be locked}"
    : "${ECASH_MIN_FREE_PERCENT:?ECASH_MIN_FREE_PERCENT must be locked}"
    : "${ECASH_ACTIVATION_HEIGHT:?ECASH_ACTIVATION_HEIGHT must be locked}"
    : "${ECASH_ACTIVATION_BLOCK_HASH:?ECASH_ACTIVATION_BLOCK_HASH must be locked}"
    : "${ECASH_SNAPSHOT_FILE:?ECASH_SNAPSHOT_FILE must be locked}"
    : "${ECASH_SNAPSHOT_URL:?ECASH_SNAPSHOT_URL must be locked}"
    : "${ECASH_SNAPSHOT_CHECKSUMS_URL:?ECASH_SNAPSHOT_CHECKSUMS_URL must be locked}"
    : "${ECASH_SNAPSHOT_SIZE:?ECASH_SNAPSHOT_SIZE must be locked}"
    : "${ECASH_SNAPSHOT_SHA256:?ECASH_SNAPSHOT_SHA256 must be locked}"
    : "${ENFORCER_NETWORK_PRESET:?ENFORCER_NETWORK_PRESET must be locked}"
    : "${ENFORCER_API_NETWORK:?ENFORCER_API_NETWORK must be locked}"
    : "${POSTGRES_IMAGE:?POSTGRES_IMAGE must be locked}"
    : "${POSTGRES_DB:?POSTGRES_DB must be locked}"
    : "${POSTGRES_USER:?POSTGRES_USER must be locked}"

    [[ "${NETWORK_ID}" =~ ^[a-z0-9][a-z0-9-]*$ ]] ||
        die "NETWORK_ID has an invalid format"
    # Both end up unquoted inside psql invocations and the healthcheck.
    [[ "${POSTGRES_DB}" =~ ^[a-z_][a-z0-9_]*$ ]] ||
        die "POSTGRES_DB has an invalid format"
    [[ "${POSTGRES_USER}" =~ ^[a-z_][a-z0-9_]*$ ]] ||
        die "POSTGRES_USER has an invalid format"
    [[ "${ECASH_ACTIVATION_BLOCK_HASH}" =~ ^[[:xdigit:]]{64}$ ]] ||
        die "ECASH_ACTIVATION_BLOCK_HASH must contain 64 hexadecimal characters"
    require_positive_integer ECASH_NODE_P2P_PORT "${ECASH_NODE_P2P_PORT}"
    require_positive_integer ECASH_NODE_RPC_PORT "${ECASH_NODE_RPC_PORT}"
    require_positive_integer ECASH_NODE_ZMQ_PORT "${ECASH_NODE_ZMQ_PORT}"
    require_positive_integer ECASH_NODE_EXPECTED_VERSION "${ECASH_NODE_EXPECTED_VERSION}"
    require_positive_integer ECASH_EXPECTED_DATA_BYTES "${ECASH_EXPECTED_DATA_BYTES}"
    require_positive_integer ECASH_MIN_FREE_PERCENT "${ECASH_MIN_FREE_PERCENT}"
    require_positive_integer ECASH_ACTIVATION_HEIGHT "${ECASH_ACTIVATION_HEIGHT}"
    require_positive_integer ECASH_SNAPSHOT_SIZE "${ECASH_SNAPSHOT_SIZE}"
    ((ECASH_MIN_FREE_PERCENT < 100)) ||
        die "ECASH_MIN_FREE_PERCENT must be less than 100"
    network_peers >/dev/null
}

network_peers() {
    local host
    local peer
    local port
    local -a peers

    IFS=',' read -r -a peers <<<"${ECASH_PUBLIC_PEERS}"
    ((${#peers[@]} > 0)) || die "ECASH_PUBLIC_PEERS must not be empty"
    for peer in "${peers[@]}"; do
        [[ "${peer}" != *[[:space:]]* && "${peer}" == *:* ]] ||
            die "invalid locked peer: ${peer}"
        host="${peer%:*}"
        port="${peer##*:}"
        [[ "${host}" =~ ^[a-zA-Z0-9.-]+$ ]] ||
            die "invalid locked peer hostname: ${host}"
        [[ "${port}" == "${ECASH_NODE_P2P_PORT}" ]] ||
            die "locked peer ${peer} does not use ECASH_NODE_P2P_PORT=${ECASH_NODE_P2P_PORT}"
        printf '%s\n' "${peer}"
    done
}

render_node_config() {
    local destination="$1"
    local peer
    local temporary_config
    local template="${DEPLOYMENT_ROOT}/config/ecash.conf.template"

    [[ -f "${template}" ]] || die "missing node configuration template: ${template}"
    temporary_config="$(mktemp "${destination}.XXXXXX")"
    if ! cp "${template}" "${temporary_config}"; then
        rm -f -- "${temporary_config}"
        die "could not copy the node configuration template"
    fi
    {
        printf '\n# Locked network values. Generated by scripts/init.sh.\n'
        printf '# network_id=%s magic=%s\n' "${NETWORK_ID}" "${ECASH_NETWORK_MAGIC}"
        printf 'port=%s\n' "${ECASH_NODE_P2P_PORT}"
        printf 'rpcport=%s\n' "${ECASH_NODE_RPC_PORT}"
        printf 'zmqpubsequence=tcp://0.0.0.0:%s\n' "${ECASH_NODE_ZMQ_PORT}"
        while IFS= read -r peer; do
            printf 'addnode=%s\n' "${peer}"
        done < <(network_peers)
    } >>"${temporary_config}"
    # The node bind-mounts this exact file, so the destination inode has to
    # survive. A replacing rename would leave the running container reading the
    # previous file while the host shows the new one.
    if ! cat -- "${temporary_config}" >"${destination}"; then
        rm -f -- "${temporary_config}"
        die "could not write the node configuration: ${destination}"
    fi
    rm -f -- "${temporary_config}"
    chmod 0644 "${destination}"
}

normalize_assignment_key() {
    local key="$1"

    key="${key#"${key%%[![:space:]]*}"}"
    key="${key%"${key##*[![:space:]]}"}"
    printf '%s\n' "${key}"
}

reject_version_overrides() {
    local env_file="$1"
    local -A locked_keys=()
    local key

    while IFS='=' read -r key _; do
        key="$(normalize_assignment_key "${key}")"
        [[ "${key}" =~ ^[A-Z][A-Z0-9_]*$ ]] || continue
        locked_keys["${key}"]=1
    done <"${VERSIONS_FILE}"

    while IFS='=' read -r key _; do
        key="$(normalize_assignment_key "${key}")"
        [[ "${key}" =~ ^[A-Z][A-Z0-9_]*$ ]] || continue
        [[ -z "${locked_keys[${key}]+present}" ]] ||
            die "${env_file} must not override locked variable ${key}"
        case "${key}" in
        COMPOSE_PROJECT_NAME | ECASH_DATA_ROOT)
            die "${env_file} must not set derived variable ${key}"
            ;;
        esac
    done <"${env_file}"
}

deployment_env_file() {
    printf '%s\n' "${COMPOSE_ENV_FILE:-${DEPLOYMENT_ROOT}/.env}"
}

load_deployment_env() {
    local env_file
    local resolved_data_base
    env_file="$(deployment_env_file)"
    [[ -f "${env_file}" ]] || die "missing ${env_file}; run 'just init' first"
    reject_version_overrides "${env_file}"

    set -a
    # The local file is created from the repository's simple KEY=VALUE example.
    # shellcheck disable=SC1090
    source "${env_file}"
    set +a

    : "${ECASH_DATA_BASE:?ECASH_DATA_BASE must be set}"
    : "${PUID:?PUID must be set}"
    : "${PGID:?PGID must be set}"
    [[ "${PUID}" =~ ^[0-9]+$ ]] || die "PUID must be numeric"
    [[ "${PGID}" =~ ^[0-9]+$ ]] || die "PGID must be numeric"
    require_positive_integer \
        ENFORCER_SYNC_WAIT_SECONDS "${ENFORCER_SYNC_WAIT_SECONDS:-300}"
    require_positive_integer \
        SNAPSHOT_HEADER_WAIT_SECONDS "${SNAPSHOT_HEADER_WAIT_SECONDS:-1800}"
    require_positive_integer \
        MONITOR_STARTUP_WAIT_SECONDS "${MONITOR_STARTUP_WAIT_SECONDS:-60}"
    require_positive_integer \
        MONITOR_EVENT_WAIT_SECONDS "${MONITOR_EVENT_WAIT_SECONDS:-60}"
    require_positive_integer \
        LIVE_BLOCK_WAIT_SECONDS "${LIVE_BLOCK_WAIT_SECONDS:-3600}"
    require_positive_integer \
        LIVE_EVENT_WAIT_SECONDS "${LIVE_EVENT_WAIT_SECONDS:-60}"

    # Restore every repository pin after loading operator-owned configuration.
    load_versions

    if [[ "${ECASH_DATA_BASE}" == /* ]]; then
        resolved_data_base="$(realpath -m -- "${ECASH_DATA_BASE}")"
    else
        resolved_data_base="$(realpath -m -- "${DEPLOYMENT_ROOT}/${ECASH_DATA_BASE}")"
    fi
    [[ "${resolved_data_base}" != / ]] || die "ECASH_DATA_BASE must not resolve to /"
    COMPOSE_PROJECT_NAME="bip300-ecash-${NETWORK_ID}"
    ECASH_DATA_ROOT="$(realpath -m -- "${resolved_data_base}/${NETWORK_ID}")"
    export COMPOSE_PROJECT_NAME ECASH_DATA_ROOT
}

data_root() {
    : "${ECASH_DATA_ROOT:?load deployment environment before resolving its data root}"
    printf '%s\n' "${ECASH_DATA_ROOT}"
}

compose() {
    local env_file
    env_file="$(deployment_env_file)"
    docker compose \
        --env-file "${env_file}" \
        --env-file "${VERSIONS_FILE}" \
        --file "${DEPLOYMENT_ROOT}/compose.yaml" \
        "$@"
}

node_cli() {
    compose exec -T ecash-node \
        bitcoin-cli \
        -datadir=/data \
        -conf=/etc/ecash/ecash.conf \
        -rpcport="${ECASH_NODE_RPC_PORT}" \
        "$@"
}

service_is_running() {
    [[ -n "$(compose ps --status running --quiet "$1")" ]]
}

require_service_running() {
    service_is_running "$1" || die "$1 is not running"
}

service_started_at() {
    local container_id
    container_id="$(compose ps --status running --quiet "$1")"
    [[ -n "${container_id}" ]] || die "$1 is not running"
    docker inspect --format '{{.State.StartedAt}}' "${container_id}"
}

enforcer_rpc() {
    local method="$1"
    compose exec -T enforcer \
        curl --fail-with-body --silent --show-error --max-time 30 \
        --request POST \
        --header 'Content-Type: application/json' \
        --data '{}' \
        "http://127.0.0.1:50051/cusf.mainchain.v1.ValidatorService/${method}"
}

nats_monitor() {
    local endpoint="$1"
    compose exec -T nats \
        wget -qO- "http://127.0.0.1:8222${endpoint}"
}

nats_is_healthy() {
    local health
    health="$(nats_monitor /healthz 2>/dev/null)" &&
        jq -e '.status == "ok"' <<<"${health}" >/dev/null
}

nats_has_client() {
    local client_name="$1"
    local connections
    connections="$(nats_monitor /connz 2>/dev/null)" &&
        jq -e --arg client_name "${client_name}" \
            '.connections | any(.name == $client_name)' \
            <<<"${connections}" >/dev/null
}

nats_has_enforcer_subscription() {
    local subscriptions
    subscriptions="$(nats_monitor '/subsz?subs=true' 2>/dev/null)" &&
        jq -e \
            '.subscriptions_list | any(.account == "$G" and .subject == "bip300.enforcer")' \
            <<<"${subscriptions}" >/dev/null
}

wait_for_nats_health() {
    local wait_seconds="${MONITOR_STARTUP_WAIT_SECONDS:-60}"
    local deadline="$((SECONDS + wait_seconds))"
    until nats_is_healthy; do
        ((SECONDS < deadline)) ||
            die "Core NATS was not healthy after ${wait_seconds}s"
        sleep 2
    done
}

wait_for_event_logger_subscription() {
    local wait_seconds="${MONITOR_STARTUP_WAIT_SECONDS:-60}"
    local deadline="$((SECONDS + wait_seconds))"
    until nats_has_client bip300-monitor-event-logger &&
        nats_has_enforcer_subscription; do
        ((SECONDS < deadline)) ||
            die "event logger subscription was not ready after ${wait_seconds}s"
        sleep 2
    done
}

postgres_psql() {
    compose exec -T postgres \
        psql --username="${POSTGRES_USER}" --dbname="${POSTGRES_DB}" \
        --no-align --tuples-only --quiet "$@"
}

postgres_is_healthy() {
    compose exec -T postgres \
        pg_isready --host=127.0.0.1 \
        --username="${POSTGRES_USER}" --dbname="${POSTGRES_DB}" >/dev/null 2>&1
}

wait_for_postgres_health() {
    local wait_seconds="${MONITOR_STARTUP_WAIT_SECONDS:-60}"
    local deadline="$((SECONDS + wait_seconds))"
    until postgres_is_healthy; do
        ((SECONDS < deadline)) ||
            die "Postgres was not ready after ${wait_seconds}s"
        sleep 2
    done
}

wait_for_nats_client() {
    local client_name="$1"
    local wait_seconds="${MONITOR_STARTUP_WAIT_SECONDS:-60}"
    local deadline="$((SECONDS + wait_seconds))"
    until nats_has_client "${client_name}"; do
        ((SECONDS < deadline)) ||
            die "NATS client ${client_name} was not connected after ${wait_seconds}s"
        sleep 2
    done
}

line_contains_sidechain() {
    local line="$1"
    local sidechain="$2"
    local slot_pattern

    [[ "${sidechain}" =~ ^[0-9]+$ ]] || return 1
    slot_pattern="(^|[[:space:]])(summary=\"?)?sidechain=${sidechain}([^0-9]|$)"
    [[ "${line}" =~ ${slot_pattern} ]]
}

logs_contain_live_event() {
    local logs="$1"
    local message="$2"
    local sidechain="$3"
    local block_hash="$4"
    local line

    [[ "${sidechain}" =~ ^[0-9]+$ ]] || return 1

    while IFS= read -r line; do
        if [[ "${line}" == *"${message}"* ]] &&
            line_contains_sidechain "${line}" "${sidechain}" &&
            [[ "${line}" == *"${block_hash}"* ]]; then
            return 0
        fi
    done <<<"${logs}"
    return 1
}

logs_contain_message() {
    local logs="$1"
    local message="$2"
    [[ "${logs}" == *"${message}"* ]]
}

logs_contain_snapshot_completion() {
    local logs="$1"
    local sidechain_count="$2"
    local count_pattern
    local line

    [[ "${sidechain_count}" =~ ^[0-9]+$ ]] || return 1
    count_pattern="(^|[[:space:]])sidechain_count=${sidechain_count}([^0-9]|$)"
    while IFS= read -r line; do
        if [[ "${line}" == *"published initial enforcer snapshot"* &&
            "${line}" =~ ${count_pattern} ]]; then
            return 0
        fi
    done <<<"${logs}"
    return 1
}

count_snapshot_events() {
    local logs="$1"
    local kind="$2"
    local sidechain="${3:-}"
    local count=0
    local event_pattern
    local line

    [[ "${kind}" =~ ^[a-z_]+$ ]] || return 1
    event_pattern="(^|[[:space:]])event=\"?${kind}\"?([[:space:]]|$)"
    if [[ -n "${sidechain}" ]]; then
        [[ "${sidechain}" =~ ^[0-9]+$ ]] || return 1
    fi

    while IFS= read -r line; do
        [[ "${line}" == *"received enforcer event"* ]] || continue
        [[ "${line}" =~ ${event_pattern} ]] || continue
        if [[ -n "${sidechain}" ]] &&
            ! line_contains_sidechain "${line}" "${sidechain}"; then
            continue
        fi
        ((count += 1))
    done <<<"${logs}"
    printf '%s\n' "${count}"
}

# The extractor republishes a snapshot kind whenever a block changes it, so a
# verification window can legitimately hold more than one of them. Only the
# kinds that are published exactly once may be counted exactly.
has_snapshot_event() {
    local count

    count="$(count_snapshot_events "$@")" || return 1
    [[ "${count}" =~ ^[0-9]+$ ]] || return 1
    ((count >= 1))
}

normalize_timestamp() {
    local timestamp="$1"
    local fraction
    local prefix

    # Docker renders StartedAt with Go's RFC3339Nano, which strips trailing
    # zeros. Pad the fraction back to a fixed width so two instants can be
    # compared as plain strings.
    if [[ "${timestamp}" =~ ^([0-9-]+T[0-9:]+)(\.([0-9]+))?Z$ ]]; then
        prefix="${BASH_REMATCH[1]}"
        fraction="${BASH_REMATCH[3]}"
        while ((${#fraction} < 9)); do
            fraction="${fraction}0"
        done
        printf '%s.%sZ\n' "${prefix}" "${fraction}"
        return 0
    fi
    printf '%s\n' "${timestamp}"
}

latest_timestamp() {
    local first="$1"
    local second="$2"
    if [[ "$(normalize_timestamp "${first}")" > "$(normalize_timestamp "${second}")" ]]; then
        printf '%s\n' "${first}"
    else
        printf '%s\n' "${second}"
    fi
}

require_activation_header() {
    local header
    header="$(node_cli getblockheader "${ECASH_ACTIVATION_BLOCK_HASH}")" ||
        die "${NETWORK_ID} activation header is unavailable"
    jq -e \
        --arg hash "${ECASH_ACTIVATION_BLOCK_HASH}" \
        --argjson height "${ECASH_ACTIVATION_HEIGHT}" \
        '.hash == $hash and .height == $height' <<<"${header}" >/dev/null ||
        die "unexpected ${NETWORK_ID} activation header"
}

require_activation_block() {
    local activation_hash
    activation_hash="$(node_cli getblockhash "${ECASH_ACTIVATION_HEIGHT}")" ||
        die "${NETWORK_ID} activation block is unavailable"
    [[ "${activation_hash}" == "${ECASH_ACTIVATION_BLOCK_HASH}" ]] ||
        die "unexpected block at height ${ECASH_ACTIVATION_HEIGHT}: ${activation_hash}"
}

require_rpc_cookie_readable() {
    local cookie
    local cookie_gid
    local cookie_mode
    local cookie_uid
    local mode

    cookie="$(data_root)/rpc-cookie/.cookie"
    [[ -f "${cookie}" ]] ||
        die "the node RPC cookie does not exist yet: ${cookie}; wait for ecash-node to finish starting"

    read -r cookie_uid cookie_gid cookie_mode < <(
        stat --format='%u %g %a' "${cookie}"
    )
    mode="$((8#${cookie_mode}))"

    if [[ "${cookie_uid}" == "${PUID}" ]] && ((mode & 0400)); then
        return 0
    fi
    if [[ "${cookie_gid}" == "${PGID}" ]] && ((mode & 0040)); then
        return 0
    fi
    if ((mode & 0004)); then
        return 0
    fi

    die "the node RPC cookie ${cookie} is owned by ${cookie_uid}:${cookie_gid} with mode ${cookie_mode}, but the enforcer runs as ${PUID}:${PGID} and cannot read it; the node image did not honour UID/GID"
}

require_node_peer() {
    local peer_count
    peer_count="$(node_cli getconnectioncount)" ||
        die "ecash-node did not return a peer count"
    [[ "${peer_count}" =~ ^[0-9]+$ ]] ||
        die "ecash-node returned an invalid peer count: ${peer_count}"
    ((peer_count > 0)) || die "ecash-node has no ${NETWORK_ID} peers"
}

require_node_ready() {
    local blockchain_info
    require_service_running ecash-node
    blockchain_info="$(node_cli getblockchaininfo)"

    jq -e --arg chain "${ECASH_NODE_CHAIN}" '.chain == $chain' \
        <<<"${blockchain_info}" >/dev/null ||
        die "ecash-node is not using the expected ${NETWORK_ID} chain"
    jq -e --argjson height "${ECASH_ACTIVATION_HEIGHT}" \
        '.blocks >= $height and .headers >= $height' \
        <<<"${blockchain_info}" >/dev/null ||
        die "ecash-node has not reached ${NETWORK_ID} activation height ${ECASH_ACTIVATION_HEIGHT}"
    jq -e '.initialblockdownload == false' <<<"${blockchain_info}" >/dev/null ||
        die "ecash-node is still in initial block download"

    require_activation_block
    require_node_peer
}

node_history_is_ready() {
    local chainstates="${1:-}"

    if [[ -z "${chainstates}" ]]; then
        chainstates="$(node_cli getchainstates 2>/dev/null)" || return 1
    fi

    jq -e --argjson activation_height "${ECASH_ACTIVATION_HEIGHT}" '
        (.chainstates | type == "array")
        and (.chainstates | length == 1)
        and (.chainstates[0].validated == true)
        and (.chainstates[0].blocks >= $activation_height)
    ' <<<"${chainstates}" >/dev/null 2>&1
}

require_node_history_ready() {
    local active_blocks
    local chainstate_count
    local chainstates
    local historical_blocks

    chainstates="$(node_cli getchainstates)" ||
        die "ecash-node did not return chainstate information"
    jq -e '.chainstates | type == "array" and length >= 1' \
        <<<"${chainstates}" >/dev/null ||
        die "ecash-node returned no usable chainstate"

    node_history_is_ready "${chainstates}" && return 0

    chainstate_count="$(jq -r '.chainstates | length' <<<"${chainstates}")"
    historical_blocks="$(jq -r '.chainstates[0].blocks // "unavailable"' <<<"${chainstates}")"
    active_blocks="$(jq -r '.chainstates[-1].blocks // "unavailable"' <<<"${chainstates}")"
    die "ecash-node history is not ready (chainstates=${chainstate_count}, historical_blocks=${historical_blocks}, active_blocks=${active_blocks}); wait until 'getchainstates' reports one validated chainstate at or above activation height ${ECASH_ACTIVATION_HEIGHT}"
}
